### ISSUE TITLE
Add PLUGIN_BRANCH for Automatically Populating Branch Information in Build Post Call

### ISSUE THREAD

**Issue by Ompragash** [drone/drone-jira#23]
## Description:
This enhancement proposes adding a new plugin configuration option PLUGIN_BRANCH. When this option is enabled, the plugin will automatically populate the branch name and repository URI (similar to how Jenkins’ Jira plugin works) in the build post call to Jira. If PLUGIN_BRANCH is not passed, the plugin will continue with its current behavior without including branch information.

## Problem:
Currently, the Drone Jira plugin does not include any branch-specific information (e.g., branch name and repository URI) in the build post call to Jira. This limits the plugin’s usefulness in environments where multiple branches are in use, such as feature or bugfix branches, as branch-specific details aren’t tracked. Without these details, users can’t easily trace which branch a particular build came from in Jira.

## Solution:
Add a new PLUGIN_BRANCH setting to the Drone Jira plugin. When enabled, the plugin will automatically extract the branch name and repository URI from the build context and pass this information in the build payload to Jira. This behavior will mirror the way Jenkins’ Jira plugin works.

If PLUGIN_BRANCH is not set, the plugin will behave as it currently does, excluding the branch information from the payload. This ensures that existing users aren’t impacted by this change.

## Example Usage:
1. If PLUGIN_BRANCH is passed, the build payload sent to Jira will look something like this:
```
{
  "builds": [
    {
      "buildNumber": 123,
      "description": "Sample build description",
      "displayName": "Sample Build",
      "url": "https://your-ci-system/build/123",
      "lastUpdated": "2024-09-12T10:00:00Z",
      "pipelineId": "your-pipeline-id",
      "issueKeys": ["ISSUE-123"],
      "state": "successful",
      "updateSequenceNumber": 123,
      "references": [
        {
          "commit": {
            "id": "08cd9c26b2b8d7cf6e6af6b49da8895d065c259f",
            "repositoryUri": "https://bitbucket.org/atlassian/biij-vendor-api"
          },
          "ref": {
            "name": "feature/ISSUE-123-some-work",
            "uri": "https://bitbucket.org/atlassian/biij-vendor-api/refs/feature/ISSUE-123-some-work"
          }
        }
      ]
    }
  ]
}
```

2. If PLUGIN_BRANCH is not passed, the references field will simply be omitted.

**Comment by bradrydzewski** [comment]
@Ompragash branch and repository are automatically passed to every plugin vs the `DRONE_BRANCH` environment variable, so we should not need to ask the user to specify branch.  You can see a list of environment variables automatically passed to all plugins here:  https://docs.drone.io/pipeline/environment/reference/

here you can see how we use these for the Slack plugin:
https://github.com/drone-plugins/drone-slack/blob/master/main.go#L106

**Comment by Ompragash** [comment]
Added in #26
